services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent:/config
      - ./data/downloads:/downloads
    ports:
      - <port>:8080
      - <port>:6881
      - <port>:6881/udp
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    volumes:
      - ./config/prowlarr:/config
    ports:
      - <port>:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config/radarr:/config
      - ./data/movies:/movies
      - ./data/downloads:/downloads
    ports:
      - <port>:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config/sonarr:/config
      - ./data/series:/series
      - ./data/downloads:/downloads
    ports:
      - <port>:8989
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    volumes:
      - ./config/jellyfin:/config
      - ./data:/media
    ports:
      - <port>:8096
    restart: unless-stopped
